### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by JohnnyBekkestad** [bobthecow/genghis#124]
## I tried the gem installer and this is the error i got

 c:\Utils>gem install genghisapp
Temporarily enhancing PATH to include DevKit...
Building native extensions. This could take a while...
ERROR: Error installing genghisapp:
ERROR: Failed to build gem native extension.

C:/Ruby200-x64/bin/ruby.exe extconf.rb
checking for main() in -lssl... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
creating Makefile

make
generating rubyeventmachine-x64-mingw32.def
compiling binder.cpp
In file included from c:\devkit\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/pro
cess.h:12:0,
from c:/Ruby200-x64/include/ruby-2.0.0/ruby/win32.h:60,
from c:/Ruby200-x64/include/ruby-2.0.0/ruby/defines.h:153,
from c:/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:70,
from c:/Ruby200-x64/include/ruby-2.0.0/ruby.h:33,
from em.h:24,
from project.h:150,
from binder.cpp:20:
c:\devkit\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/sys/types.h:68:16: error:
conflicting declaration 'typedef _pid_t pid_t'
In file included from binder.cpp:20:0:
project.h:97:13: error: 'pid_t' has a previous declaration as 'typedef int pid_t'
In file included from project.h:151:0,
from binder.cpp:20:
ed.h: In member function 'void EventableDescriptor::SetSocketInvalid()':
ed.h:43:40: warning: overflow in implicit constant conversion [-Woverflow]
make: **\* [binder.o] Error 1

Gem files will remain installed in C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3 for inspection.
## Then i tried to just run the genghis.rb instead and i got this error

c:\genghis-2.3.6>ruby genghis.rb
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/custom_require.rb:36:in `require': cannot load such file -- mongo (Load
Error)
from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/custom_require.rb:36:in`require'

**Comment by bobthecow** [comment]
Heh. Windows + Ruby + native extensions is never fun. If you're not already using Ruby for other things, it's often easier to use the PHP backend on Windows.

It looks like the gem that's failing is eventmachine. [It has a native Windows build](http://rubygems.org/gems/eventmachine/versions), so I'm not entirely sure why your system is trying to build it rather than use that one. Try installing just that gem with a specific version that we know has a native build:

```
gem install eventmachine --version 1.0.3
```

**Comment by JohnnyBekkestad** [comment]
That did not work either... I am running a 64bit win8 machine, don't know if that is an issue

## Here is the output

C:\Utils>gem install eventmachine --version 1.0.3
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

```
    C:/Ruby200-x64/bin/ruby.exe extconf.rb
```

checking for main() in -lssl... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
creating Makefile

make
generating rubyeventmachine-x64-mingw32.def
compiling binder.cpp
In file included from c:\devkit\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/pro
cess.h:12:0,
                 from c:/Ruby200-x64/include/ruby-2.0.0/ruby/win32.h:60,
                 from c:/Ruby200-x64/include/ruby-2.0.0/ruby/defines.h:153,
                 from c:/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:70,
                 from c:/Ruby200-x64/include/ruby-2.0.0/ruby.h:33,
                 from em.h:24,
                 from project.h:150,
                 from binder.cpp:20:
c:\devkit\mingw\bin../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/sys/types.h:68:16: error:
 conflicting declaration 'typedef _pid_t pid_t'
In file included from binder.cpp:20:0:
project.h:97:13: error: 'pid_t' has a previous declaration as 'typedef int pid_t'
In file included from project.h:151:0,
                 from binder.cpp:20:
ed.h: In member function 'void EventableDescriptor::SetSocketInvalid()':
ed.h:43:40: warning: overflow in implicit constant conversion [-Woverflow]
make: **\* [binder.o] Error 1

Gem files will remain installed in C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3 for inspection.

## Results logged to C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/ext/gem_make.out

**Comment by JohnnyBekkestad** [comment]
There seems to be a fix for this, but how do i specify the 
gem install --version /*\* VERSION FOR THE FIX IS MISSING **/
in the http://rubygems.org/gems/eventmachine/versions the latest version is 1.0.3 which is from mars, but i need the fix from a week ago

https://github.com/eventmachine/eventmachine/pull/411

**Comment by bobthecow** [comment]
It looks like that fix hasn't been merged or released yet. You could clone the git repo for that project, patch the source, and build it yourself.

**Comment by JohnnyBekkestad** [comment]
I tried to rebuild it myself, but rake wont build either...

**Comment by JohnnyBekkestad** [comment]
And it does not really tell me a lot either....

C:\Utils\eventmachine>rake build --trace
rake aborted!
Don't know how to build task 'build'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/task_manager.rb:49:in `[]'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:148:in`invoke_task'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in`each'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:115:in`run_with_threads'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:78:in`block in run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib/rake/application.rb:75:in`run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
C:/Ruby200-x64/bin/rake:23:in`load'
C:/Ruby200-x64/bin/rake:23:in `<main>'

**Comment by ccoenen** [comment]
I would like to promote this patch to event machine, which works for me: https://github.com/eventmachine/eventmachine/issues/451

Maybe some of you are interested in testing this on your machines as well?
