### ISSUE TITLE
Mustache errors

### ISSUE THREAD

**Issue by mattmorten** [bobthecow/genghis#181]
I run /usr/bin/genghisapp (having installed from gem) and I receive the following error:

`/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require': /Library/Ruby/Gems/1.8/gems/sinatra-mustache-0.3.1/lib/sinatra/helpers/mustache.rb:10: syntax error, unexpected tIDENTIFIER, expecting tAMPER (SyntaxError)
          add_to_mustache_helper_methods(*arg.instance_methods, arg)
                                                                   ^
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/sinatra-mustache-0.3.1/lib/sinatra/mustache.rb:2
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/genghisapp-2.3.11/genghis.rb:870
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/genghisapp-2.3.11/bin/genghisapp:9
    from /usr/bin/genghisapp:19:in`load'
    from /usr/bin/genghisapp:19`

**Comment by bobthecow** [comment]
What versions of `mustache`, `sinatra`, and `genghisapp` gems are you running? What Ruby version?

**Comment by aaronup** [comment]
@bobthecow, same error for me as well...

Here's the details:
mustache (0.99.5)
sinatra (1.4.5)
sinatra-contrib (1.4.2)
sinatra-mustache (0.3.1)

Note, these are the versions getting installed via dependencies via `$ gem install genghisapp` 

genghisapp (2.3.11)
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin11.0]

Thanks for looking into it

**Comment by mattmorten** [comment]
My versions are identical to aaronup, with exception of:

ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
