### ISSUE TITLE
genghisapp bin crashes on launch

### ISSUE THREAD

**Issue by tyler-johnson** [bobthecow/genghis#40]
I type `genghisapp` into the terminal after a successful gem install and this is what I get:

```
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /Library/Ruby/Gems/1.8/gems/genghisapp-2.1.0/genghis.rb:644: odd number list for Hash (SyntaxError)
          error(status, {error: message, status: status}.to_json)
                               ^
/Library/Ruby/Gems/1.8/gems/genghisapp-2.1.0/genghis.rb:644: syntax error, unexpected ':', expecting '}'
          error(status, {error: message, status: status}.to_json)
                               ^
/Library/Ruby/Gems/1.8/gems/genghisapp-2.1.0/genghis.rb:644: syntax error, unexpected ':', expecting '='
          error(status, {error: message, status: status}.to_json)
                                                ^
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/genghisapp-2.1.0/bin/genghisapp:9
    from /usr/bin/genghisapp:19:in `load'
    from /usr/bin/genghisapp:19
```

Suggestions?

**Comment by bobthecow** [comment]
Sorry about that, and thanks for the report. This has been fixed in v2.1.1.
